name: Update README Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Update image URL in README
        run: |
          sed -i "s|\(github-readme-stats.vercel.app/api/top-langs/.*hide_title=true\).*'|\1\&ts=${{ env.TIMESTAMP }}'|g" README.md

      - name: Commit and push (if changes)
        run: |
          git config --local user.email "levi.pires2005@gmail.com"
          git config --local user.name "levisantosp"
          git add README.md
          
          if ! git diff --staged --quiet; then
            git commit -m "chore: update README stats timestamp 🤖"
            git push
          else
            echo "No changes needed."
          fi
